### ISSUE TITLE
A new home

### ISSUE THREAD

**Issue by reaperhulk** [python-tls/tls#132]
Hey pyca/tls folks,

@alex and I have been conversing recently about the scope of PyCA and what's appropriate to live under our banner. We'd like PyCA to be more tightly focused due to our limited people power and while this project is a cool idea it's still experimental and will remain so for the foreseeable future. So, I'd like to propose that we move this to its own org for now and as the project matures we can potentially revisit its inclusion.

If you have reasons why we shouldn't do this, please let me know!

**Comment by ashfall** [comment]
Sounds reasonable. :) Thanks for helping this project set up and get to this point! 

We'll work on setting up org and transferring the repo in the next few days. Hoping for a smooth transition!

**Comment by markrwilliams** [comment]
@reaperhulk I've invited you to be an administrator of https://github.com/python-tls.  This should allow you to transfer `tls` over at your convenience.

**Comment by markrwilliams** [comment]
And here we are!  Thanks!
